#!/bin/bash
#PBS -N hetmer_excl
#PBS -l select=1:ncpus=64:mem=800gb
#PBS -l walltime=2:00:00
#PBS -M dwl25@imperial.ac.uk
set -euo pipefail
cd $PBS_O_WORKDIR
mkdir -p hetmer_excl_logs
module load miniforge/3
eval "$(~/miniforge3/bin/conda shell.bash hook)"
conda activate snakemake 
echo "Running on node: $(hostname)"

snakemake -s multiparam_set.smk \
    --cores $NCPUS\
    --keep-going \
    --printshellcmds \
    --config exp=src/config/hetmer_excl.yaml

