import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from src.model_call import ModelCall
from src.config import model_param, model_var
import numpy as np


rates = model_param.copy()
rates['k_s_in'] = 10.0
rates['k_n_in'] = 5.0
rates['k_bind_s'] = 1.0
rates['k_bind_n'] = 1.0
rates['k_unbind_s'] = 0.5
rates['k_unbind_n'] = 0.5
rates['k_dimerise'] = 2.0
rates['k_dissociate'] = 1.0
rates['k_prod_m'] = 5.0
rates['k_deg_m'] = 0.1
rates['k_s_out'] = 0.5
rates['k_n_out'] = 0.5

print("Initializing model...")
model = ModelCall(
    model_param=rates,
    model_var=model_var,
    model_binding_sites=10,
    sim_max_time=100
)

print("Running trajectory...")
try:
    df_states, df_dwell, df_rxns = model.run_trajectory()
    print("Success!")
except Exception as e:
    print(f"Failed: {e}")
    smod = model.smod
    print("Extracting intermediate StochPy logs...")
    try:
        smod.GetTrajectoryData(1)
    except Exception as e2:
        print(f"GetTrajectoryData also failed: {e2}")
        import pandas as pd
        # Read the raw .dat file generated by StochPy
        dat_file = os.path.join(smod.temp_dir, f"{smod.model_file}1.dat")
        if os.path.exists(dat_file):
            print(f"Reading {dat_file}")
            df = pd.read_table(dat_file, sep='\s+', header=None)
            print("Tail of raw .dat output:")
            print(df.tail(10))
        else:
            print("Raw .dat file does not exist.")
